language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - 'hhvm'

before_script:
    - composer self-update --no-interaction
    - composer install --no-interaction --prefer-source
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls

matrix:
    allow_failures:
        - php: 'hhvm'
